import { app } from "/scripts/app.js";
import { api } from "/scripts/api.js";
import { GJJ_Utils, queueOnlyCurrentNode } from "./gjj_utils.js";

const TYPE = "GJJ_Krea2VisualOutpaint";
const PAUSED_LINK = "gjj_krea2_visual_outpaint_paused_link";
const PANEL_WIDGET = "krea2_visual_outpaint";
const FIELD_LABELS = {
  prompt:"正向提示词",negative_prompt:"反向提示词",seed:"随机种子",steps:"采样步数",cfg:"提示词引导强度",
  denoise:"降噪强度",grow_mask_by:"遮罩扩张",keep_model_loaded:"保持模型加载",
};
const HIDDEN = ["canvas_width","canvas_height","canvas_state","local_image_data","prompt","negative_prompt","unet_name","clip_name","vae_name","lora_1","lora_1_strength","lora_2","lora_2_strength","seed","steps","cfg","sampler_name","scheduler","denoise","grow_mask_by","keep_model_loaded","total_pixels_k"];
const widget = (n, name) => n.widgets?.find(w => w.name === name);
const value = (n, name, fallback="") => widget(n,name)?.value ?? fallback;
const setValue = (n,name,v) => { const w=widget(n,name); if(w){w.value=v;w.callback?.(v);} n.setDirtyCanvas?.(true,true); };
const filename = s => String(s||"").replaceAll("\\","/").split("/").pop().replace(/\.(safetensors|ckpt|pt|pth|bin|gguf)$/i,"");
const groupStem = s => filename(s).replace(/(?:^|[_\-.])(v?\d+(?:[._-]\d+)*|fp\d+|bf16|int\d+|q\d+|quant(?:ized)?|convrot|turbo)(?=$|[_\-.])/ig," ").replace(/[_\-.]+/g," ").replace(/\s+/g," ").trim();

function modelEntries(node){
  return [
    ["unet_name","主模型","models/diffusion_models","🟣"], ["clip_name","文本编码器","models/text_encoders","🟡"],
    ["vae_name","VAE","models/vae","🔴"], ["lora_1","LoRA 1","models/loras","🟠"], ["lora_2","LoRA 2","models/loras","🟠"],
  ].map(([name,label,folder,icon])=>{ const w=widget(node,name); return {widget:name,label,folder,icon,models:w?.options?.values||[],fallback:String(w?.value||""),searchValue:groupStem(w?.value),stateSearchValue:groupStem(w?.value),autoSelect:true,floatingChoices:false,getWidget:()=>w}; });
}
function button(text,title,fn){ const b=document.createElement("button"); b.textContent=text;b.title=title;b.style.cssText="height:30px;min-width:34px;border:1px solid #43545c;border-radius:7px;background:#182329;color:#fff;cursor:pointer";b.onclick=fn;return b; }
function popup(node,title,build,anchor){node.__k2Popup?.remove();const p=document.createElement("div");p.style.cssText="position:fixed;z-index:10020;width:min(560px,calc(100vw - 16px));overflow:auto;padding:12px;border:1px solid #50656e;border-radius:10px;background:#111a1f;color:#eee;box-shadow:0 12px 40px #000b;box-sizing:border-box";const h=document.createElement("div");h.textContent=title;h.style.cssText="font-weight:700;margin-bottom:10px";const x=button("✕","关闭",()=>{p.remove();node.__k2Popup=null;});x.style.float="right";h.appendChild(x);p.appendChild(h);build(p);document.body.appendChild(p);const r=anchor?.getBoundingClientRect?.()||{left:8,bottom:8};const gap=6;let left=r.left;const top=r.bottom+gap;const box=p.getBoundingClientRect();left=Math.max(8,Math.min(left,window.innerWidth-box.width-8));p.style.left=`${left}px`;p.style.top=`${top}px`;p.style.maxHeight=`${Math.max(120,window.innerHeight-top-8)}px`;node.__k2Popup=p;}
function field(node,name,label,type="text"){ const r=document.createElement("label");r.style.cssText="display:grid;grid-template-columns:120px 1fr;gap:8px;align-items:center;margin:6px 0";r.append(label);const i=document.createElement(type==="textarea"?"textarea":"input");if(type!=="textarea")i.type=type;i.value=value(node,name);i.onchange=()=>{const next=type==="number"?Number(i.value):i.value;setValue(node,name,next);if(name==="canvas_width"||name==="canvas_height")setValue(node,"total_pixels_k",0);if(name==="total_pixels_k"&&next>0){const w=Math.max(1,Number(value(node,"canvas_width",1600))),h=Math.max(1,Number(value(node,"canvas_height",1200))),ratio=w/h,pixels=next*1000;setValue(node,"canvas_width",Math.max(64,Math.round(Math.sqrt(pixels*ratio)/8)*8));setValue(node,"canvas_height",Math.max(64,Math.round(Math.sqrt(pixels/ratio)/8)*8));}node.__drawK2?.();};r.appendChild(i);return r; }
function imageUrl(ref){ if(!ref?.filename)return "";const q=new URLSearchParams({filename:ref.filename,subfolder:ref.subfolder||"",type:ref.type||"temp"});return api.apiURL(`/view?${q}`); }
async function upload(file){const f=new FormData();f.append("image",file,file.name);f.append("type","input");f.append("overwrite","true");f.append("subfolder","gjj_krea2_visual_outpaint");const r=await api.fetchApi("/upload/image",{method:"POST",body:f});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j?.error||`上传失败：HTTP ${r.status}`);const name=String(j?.name||j?.filename||file.name);return {filename:name,subfolder:String(j?.subfolder||"gjj_krea2_visual_outpaint"),type:"input"};}
function hideWidget(w){if(!w)return;w.hidden=true;w.options=w.options||{};w.options.hidden=true;w.origType=w.origType||w.type;w.type="hidden";w.computeSize=()=>[0,-4];}
function hidePreviewWidget(item){if(!item)return;item.hidden=true;item.type="hidden";item.serialize=false;item.serializeValue=()=>undefined;item.computeSize=()=>[0,0];item.computeLayoutSize=()=>({minWidth:0,minHeight:0});for(const key of ["element","inputEl","container","dom","root"]){item?.[key]?.remove?.();}}
function isNativePreviewWidget(node,item){if(!item||item===node?.__gjjKrea2PanelWidget||item.name===PANEL_WIDGET)return false;const text=`${item.name||""} ${item.label||""} ${item.type||""} ${item.options?.type||""} ${item.constructor?.name||""}`;if(/preview|image[-_ ]?preview|canvas[-_ ]?preview/i.test(text))return true;for(const key of ["element","inputEl","container","dom","root"]){if(item?.[key]?.querySelector?.("img,canvas,video"))return true;}return false;}
function clearNativePreview(node){if(!node)return;for(const key of ["imgs","images","_imgs","_images","imageRects","animatedImages"]){try{node[key]=[];}catch{}}for(const key of ["image","imageIndex","overIndex","preview","previews"]){try{node[key]=null;}catch{}}node.hideOutputImages=true;if(Array.isArray(node.widgets)){for(let i=node.widgets.length-1;i>=0;i--){if(isNativePreviewWidget(node,node.widgets[i])){hidePreviewWidget(node.widgets[i]);node.widgets.splice(i,1);}}}node.setSize?.([Math.max(260,node.size?.[0]||0),Math.max(180,node.__k2DesiredHeight||node.size?.[1]||460)]);node.setDirtyCanvas?.(true,true);}
function install(node){
  if(!node || node.__gjjKrea2PanelWidget)return;
  (node.widgets||[]).forEach(hideWidget); node.size=[Math.max(260,node.size?.[0]||0),Math.max(420,node.size?.[1]||0)];
  const root=document.createElement("div");root.style.cssText="display:flex;flex-direction:column;height:auto;gap:6px;background:#10181c;color:#fff;padding:6px;box-sizing:border-box";
  const bar=document.createElement("div");bar.style.cssText="display:flex;gap:5px"; const open=button("📁 打开图片","打开本地图片",()=>file.click()); const link=button("🔗","记住并断开/恢复上游连接",()=>toggleLink(node));
  const sizeButton=button("📐","画布尺寸",event=>popup(node,"画布尺寸",p=>{
    p.append(field(node,"canvas_width","整体宽度","number"));
    p.append(field(node,"canvas_height","整体高度","number"));
    p.append(field(node,"total_pixels_k","总像素（千像素，0 表示按宽高）","number"));
  },event.currentTarget));
  const modelButton=button("🧠","模型参数",event=>popup(node,"模型参数",p=>{
    const tree=GJJ_Utils.createModelTreeView({node,entries:modelEntries(node),refresh:()=>node.setDirtyCanvas(true,true)});
    tree.style.maxHeight="430px";
    p.append(tree);
    p.append(field(node,"lora_1_strength","LoRA 1 强度","number"));
    p.append(field(node,"lora_2_strength","LoRA 2 强度","number"));
  },event.currentTarget));
  const otherButton=button("⚙️","其它参数",event=>popup(node,"其它参数",p=>{
    for(const name of ["prompt","negative_prompt","seed","steps","cfg","denoise","grow_mask_by"]){
      const kind=["prompt","negative_prompt"].includes(name)?"textarea":"number";
      p.append(field(node,name,FIELD_LABELS[name]||name,kind));
    }
  },event.currentTarget));
  bar.append(open,link,sizeButton,modelButton,otherButton);
  const removeButton=button("🗑","删除当前选中的图片",()=>removeSelectedImage());removeButton.style.display="none";bar.append(removeButton);
  const result=button("🖼️","切换生成结果和编辑预览",()=>{node.__showResult=!node.__showResult;removeButton.style.display="none";draw();});result.style.display="none";bar.append(result);
  const run=button("▶️","只执行当前节点",async()=>{run.disabled=true;try{await queueOnlyCurrentNode(node);}finally{run.disabled=false;}});bar.append(run);root.append(bar);
  const tip=document.createElement("div");tip.style.cssText="display:none;position:fixed;z-index:10030;grid-template-columns:repeat(2,minmax(0,120px));gap:4px;max-width:250px;padding:4px;background:#0b1013;border:1px solid #60747d;border-radius:7px;pointer-events:none";document.body.appendChild(tip);const updateTip=urls=>{node.__sourceUrls=urls.filter(Boolean);tip.replaceChildren(...node.__sourceUrls.slice(0,8).map(src=>{const im=document.createElement("img");im.src=src;im.style.cssText="display:block;width:100%;height:90px;object-fit:contain;background:#071014";return im;}));};open.onmouseenter=e=>{if(!node.__sourceUrls?.length)return;tip.style.display="grid";tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY+14}px`;};open.onmousemove=e=>{tip.style.left=`${e.clientX+14}px`;tip.style.top=`${e.clientY+14}px`;};open.onmouseleave=()=>tip.style.display="none";
  const file=document.createElement("input");file.type="file";file.accept="image/*";file.multiple=true;file.hidden=true;file.onchange=async()=>{const files=Array.from(file.files||[]).filter(item=>item.type.startsWith("image/"));if(!files.length)return;const refs=[];for(const item of files)refs.push(await upload(item));setValue(node,"local_image_data",JSON.stringify(refs));const urls=refs.map(imageUrl);updateTip(urls);await loadAll(urls);draw();file.value="";};root.append(file);
  const canvas=document.createElement("canvas");canvas.style.cssText="display:block;width:100%;height:auto;min-height:0;flex:0 0 auto;background:#0000ff;border-radius:6px;cursor:grab;touch-action:none";root.append(canvas);const ctx=canvas.getContext("2d");let imgs=[],drag=null,imageRects=[],selected=0,selectedActive=false;
  const closeResultViewer=()=>{node.__k2ResultViewer?.remove();node.__k2ResultViewer=null;};
  const openResultViewer=()=>{if(!node.__resultUrl)return;closeResultViewer();let scale=1;const viewer=document.createElement("div");viewer.title="再次点击关闭；滚轮缩放；右键图片可另存为";viewer.style.cssText="position:fixed;inset:0;z-index:10050;display:flex;align-items:center;justify-content:center;overflow:hidden;background:#000d;cursor:zoom-out";const image=document.createElement("img");image.src=node.__resultUrl;image.alt="生成结果原图";image.title="再次点击关闭；滚轮缩放；右键图片可另存为";image.draggable=false;image.style.cssText="display:block;max-width:94vw;max-height:94vh;object-fit:contain;transform-origin:center center;cursor:zoom-out;user-select:none";const applyScale=()=>{image.style.transform=`scale(${scale})`;};viewer.onclick=closeResultViewer;viewer.onwheel=event=>{event.preventDefault();event.stopPropagation();scale=Math.max(.1,Math.min(20,scale*Math.exp(-event.deltaY*.001)));applyScale();};viewer.append(image);document.body.append(viewer);node.__k2ResultViewer=viewer;};
  const state=()=>{try{return JSON.parse(value(node,"canvas_state","{}"))||{};}catch{return {};}};const save=s=>setValue(node,"canvas_state",JSON.stringify(s));
  const ensureStates=()=>{const st=state();if(!Array.isArray(st.images))st.images=[];const w=Number(value(node,"canvas_width",1600)),h=Number(value(node,"canvas_height",1200));for(let i=0;i<imgs.length;i++){if(!st.images[i])st.images[i]={x:(w-imgs[i].width)/2+(i-(imgs.length-1)/2)*24,y:(h-imgs[i].height)/2+(i-(imgs.length-1)/2)*24,scale:1};}st.images.length=imgs.length;save(st);return st;};
  const removeSelectedImage=()=>{if(!selectedActive||selected<0||selected>=imgs.length)return;imgs.splice(selected,1);const st=state();if(Array.isArray(st.images))st.images.splice(selected,1);save(st);let refs=[];try{const parsed=JSON.parse(value(node,"local_image_data","[]"));refs=Array.isArray(parsed)?parsed:(parsed?[parsed]:[]);}catch{}if(selected<refs.length)refs.splice(selected,1);setValue(node,"local_image_data",JSON.stringify(refs));updateTip(refs.map(imageUrl));selected=Math.min(selected,imgs.length-1);selectedActive=false;removeButton.style.display="none";draw();};
  const loadAll=srcs=>Promise.all(srcs.filter(Boolean).map(src=>new Promise(ok=>{const im=new Image();im.onload=()=>ok(im);im.onerror=()=>ok(null);im.src=src;}))).then(items=>{imgs=items.filter(Boolean);selected=Math.max(0,imgs.length-1);selectedActive=false;removeButton.style.display="none";ensureStates();});
  const draw=()=>{const w=Math.max(1,Number(value(node,"canvas_width",1600))),h=Math.max(1,Number(value(node,"canvas_height",1200)));const cw=Math.max(1,root.clientWidth-12),ratio=w/h;canvas.style.aspectRatio=`${w} / ${h}`;canvas.width=Math.round(cw);canvas.height=Math.max(1,Math.round(cw/ratio));const desiredHeight=Math.round(canvas.height+96);node.__k2DesiredHeight=desiredHeight;if(cw>20&&Math.abs(Number(node.size?.[1]||0)-desiredHeight)>2)node.setSize?.([Number(node.size?.[0]||cw),desiredHeight]);ctx.fillStyle="#0000ff";ctx.fillRect(0,0,canvas.width,canvas.height);imageRects=[];if(node.__showResult&&node.__resultImage){ctx.drawImage(node.__resultImage,0,0,canvas.width,canvas.height);return;}const st=ensureStates(),k=canvas.width/w;for(let i=0;i<imgs.length;i++){const im=imgs[i],s=st.images[i],sc=Number(s.scale||1),x=Number(s.x||0)*k,y=Number(s.y||0)*k,rw=im.width*sc*k,rh=im.height*sc*k;ctx.drawImage(im,x,y,rw,rh);imageRects[i]={x,y,w:rw,h:rh,k};if(selectedActive&&i===selected){ctx.save();ctx.strokeStyle="#65d6ff";ctx.lineWidth=2;ctx.setLineDash([6,4]);ctx.strokeRect(x,y,rw,rh);ctx.setLineDash([]);for(const [hx,hy] of [[x,y],[x+rw,y],[x,y+rh],[x+rw,y+rh]]){ctx.fillStyle="#f8ffff";ctx.strokeStyle="#087fa8";ctx.lineWidth=2;ctx.beginPath();ctx.rect(hx-6,hy-6,12,12);ctx.fill();ctx.stroke();}ctx.restore();}}};
  const pointerPos=e=>{const r=canvas.getBoundingClientRect();return {x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height};};
  const cornerAt=p=>{const r=imageRects[selected];if(!r)return null;const corners=[["nw",r.x,r.y],["ne",r.x+r.w,r.y],["sw",r.x,r.y+r.h],["se",r.x+r.w,r.y+r.h]];return corners.find(([,x,y])=>Math.hypot(p.x-x,p.y-y)<=14)?.[0]||null;};
  const hitImage=p=>{for(let i=imageRects.length-1;i>=0;i--){const r=imageRects[i];if(r&&p.x>=r.x&&p.x<=r.x+r.w&&p.y>=r.y&&p.y<=r.y+r.h)return i;}return -1;};
  canvas.onpointerdown=e=>{if(node.__showResult){openResultViewer();return;}if(!imgs.length)return;const p=pointerPos(e);let corner=selectedActive?cornerAt(p):null,index=corner?selected:hitImage(p);if(index<0){selectedActive=false;removeButton.style.display="none";draw();return;}selected=index;selectedActive=true;removeButton.style.display="";draw();const r=imageRects[selected],st=ensureStates(),s=st.images[selected];corner=corner||cornerAt(p);if(corner&&r){const opposite={nw:[r.x+r.w,r.y+r.h],ne:[r.x,r.y+r.h],sw:[r.x+r.w,r.y],se:[r.x,r.y]}[corner];drag={mode:"scale",corner,anchor:opposite,startDistance:Math.max(1,Math.hypot(p.x-opposite[0],p.y-opposite[1])),startScale:Number(s.scale||1),sourceW:imgs[selected].width,sourceH:imgs[selected].height,k:r.k,index:selected};canvas.style.cursor="nwse-resize";}else{drag={mode:"move",x:p.x,y:p.y,ox:Number(s.x||0),oy:Number(s.y||0),k:r.k,index:selected};canvas.style.cursor="grabbing";}canvas.setPointerCapture(e.pointerId);};
  canvas.onpointermove=e=>{const p=pointerPos(e);if(!drag){canvas.style.cursor=cornerAt(p)?"nwse-resize":(hitImage(p)>=0?"grab":"default");return;}const st=ensureStates(),s=st.images[drag.index];if(drag.mode==="move"){s.x=drag.ox+(p.x-drag.x)/drag.k;s.y=drag.oy+(p.y-drag.y)/drag.k;}else{const nextScale=Math.max(.05,Math.min(20,drag.startScale*Math.hypot(p.x-drag.anchor[0],p.y-drag.anchor[1])/drag.startDistance));s.scale=nextScale;const width=drag.sourceW*nextScale,height=drag.sourceH*nextScale,ax=drag.anchor[0]/drag.k,ay=drag.anchor[1]/drag.k;s.x=drag.corner.includes("w")?ax-width:ax;s.y=drag.corner.includes("n")?ay-height:ay;}save(st);draw();};
  canvas.onpointerup=e=>{drag=null;canvas.style.cursor="grab";try{canvas.releasePointerCapture(e.pointerId);}catch{}};canvas.onpointercancel=canvas.onpointerup;canvas.onwheel=e=>{if(node.__showResult||!imgs.length)return;e.preventDefault();const st=ensureStates(),s=st.images[selected],oldScale=Number(s.scale||1),nextScale=Math.max(.05,Math.min(20,oldScale*Math.exp(-e.deltaY*.001))),p=pointerPos(e),k=imageRects[selected]?.k||1,worldX=p.x/k,worldY=p.y/k;s.x=worldX-(worldX-Number(s.x||0))*nextScale/oldScale;s.y=worldY-(worldY-Number(s.y||0))*nextScale/oldScale;s.scale=nextScale;save(st);draw();};
  const originalConn=node.onConnectionsChange;node.onConnectionsChange=function(...a){const out=originalConn?.apply(this,a);setTimeout(sync,0);return out;};
  function savedLink(){return node.properties?.[PAUSED_LINK]||null;}
  function sync(){const linked=node.inputs?.[0]?.link!=null;const paused=savedLink();open.disabled=linked;open.style.opacity=linked?".35":"1";open.style.cursor=linked?"not-allowed":"pointer";link.style.display=(linked||paused)?"":"none";link.dataset.active=paused&&!linked?"true":"false";link.title=paused&&!linked?"恢复刚才断开的上游图片链接":"记住并断开上游图片链接";}
  function toggleLink(n){const input=n.inputs?.[0];n.properties=n.properties||{};if(input?.link!=null){const l=n.graph?.links?.[input.link];if(l)n.properties[PAUSED_LINK]={origin_id:l.origin_id,origin_slot:l.origin_slot};n.disconnectInput(0);}else{const saved=n.properties[PAUSED_LINK];if(saved){const source=n.graph?.getNodeById(saved.origin_id);if(source){source.connect(saved.origin_slot,n,0);delete n.properties[PAUSED_LINK];}}}n.setDirtyCanvas?.(true,true);sync();}
  const old=node.onExecuted;node.onExecuted=function(msg,...args){const out=old?.call(this,msg,...args);const ref=(msg?.gjj_images||msg?.images)?.[0];if(ref){const url=imageUrl(ref),im=new Image();im.onload=()=>{node.__resultImage=im;node.__resultUrl=url;node.__showResult=true;selectedActive=false;removeButton.style.display="none";result.style.display="";draw()};im.src=url;}clearNativePreview(node);for(const delay of [80,250,600])setTimeout(()=>clearNativePreview(node),delay);return out;};
  const panel=node.addDOMWidget(PANEL_WIDGET,"HTML",root,{serialize:false,hideOnZoom:false,getHeight:()=>Math.max(120,root.scrollHeight||120)});node.__gjjKrea2PanelWidget=panel||{element:root};if(panel){panel.serialize=false;panel.options=panel.options||{};panel.options.serialize=false;panel.computeSize=width=>[Math.round(Number(width||node.size?.[0]||320)),Math.max(120,root.scrollHeight||120)];}node.setSize?.([Math.max(260,node.size?.[0]||0),Math.max(300,node.size?.[1]||0)]);node.__drawK2=draw;new ResizeObserver(draw).observe(root);const local=(()=>{try{const parsed=JSON.parse(value(node,"local_image_data",""));return Array.isArray(parsed)?parsed:(parsed?[parsed]:[]);}catch{return [];}})();if(local.length){const urls=local.map(imageUrl);updateTip(urls);loadAll(urls).then(draw);}sync();clearNativePreview(node);setTimeout(draw,0);
}

function isTarget(node){return String(node?.comfyClass||node?.type||node?.constructor?.nodeData?.name||"")===TYPE;}
app.registerExtension({
  name:"GJJ.Krea2VisualOutpaint.v2",
  beforeRegisterNodeDef(nodeType,nodeData){
    if(nodeData?.name!==TYPE)return;
    nodeData.output_preview=false;
    nodeType.prototype.hideOutputImages=true;
    if(Array.isArray(nodeData.outputs))for(const output of nodeData.outputs)output.preview=false;
    const originalAddCustomWidget=nodeType.prototype.addCustomWidget;
    nodeType.prototype.addCustomWidget=function(item,...args){if(isNativePreviewWidget(this,item)){hidePreviewWidget(item);return item;}return typeof originalAddCustomWidget==="function"?originalAddCustomWidget.call(this,item,...args):item;};
    const old=nodeType.prototype.onNodeCreated;
    nodeType.prototype.onNodeCreated=function(...args){const result=old?.apply(this,args);setTimeout(()=>{install(this);clearNativePreview(this);},0);setTimeout(()=>{install(this);clearNativePreview(this);},80);return result;};
  },
  nodeCreated(node){if(isTarget(node))setTimeout(()=>install(node),0);},
  setup(){for(const node of app.graph?._nodes||[])if(isTarget(node))setTimeout(()=>install(node),0);},
});
